server:
  port: 9002
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  shutdown: graceful

spring:
  application:
    name: order-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/bookstoredb_order
    username: user
    password: password
  flyway:
    url: jdbc:postgresql://localhost:5432/bookstoredb_order
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
  cloud:
    stream:
      bindings:
        acceptOrder-out-0:
          destination: order-accepted
        dispatchOrder-in-0:
          destination: order-dispatched
          group: ${spring.application.name}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/BookOnlineStore
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    connection-timeout: 5s
# Info system
info:
  system: Bookstore system

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: info, health
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always
  info:
    os:
      enabled: true
    java:
      enabled: true
    env:
      enabled: true

bookstore:
  catalog-service-uri: "http://localhost:9001"