spring:
  r2dbc:
    url: r2dbc:postgresql://bookstore-postgres/bookstoredb_order
  flyway:
    url: jdbc:postgresql://bookstore-postgres/bookstoredb_order
  rabbitmq:
    host: bookstore-rabbitmq
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://bookstore-keycloak/realms/bookstore

bookstore:
  catalog-service-uri: http://catalog-service